App:
  RunMode: debug
  ReadTimeout: 60
  WriteTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: admin
  Password: admin
  Host: 127.0.0.1
  DBName: ${DB_NAME}
  TablePrefix: ${PREFIX_TABLE_NAME}
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
